[2022-03-11 16:39:17,319] [logger.py|__console] [line:41] INFO    : 当前执行测试用例ID-> test_login001.2 ; 测试点-> 账号为空登录
[2022-03-11 16:39:18,394] [logger.py|__console] [line:41] INFO    : 检查点-> 账号不能为空，请重新输入
[2022-03-11 16:39:18,446] [logger.py|__console] [line:41] INFO    : 登录失败，返回实际结果是->: 账号不能为空，请重新输入
